name: image-classification-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - matplotlib=3.5.2
  - pillow=9.5.0
  - scikit-learn=1.2.2
  - numpy=1.23.5
